INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, DIRECCION, CONTACTO, TIENDA_ID)
VALUES (1, 'ANA HERNANDEZ', 'PUEBLA', 22334455, 5);

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, DIRECCION, CONTACTO, TIENDA_ID)
VALUES (2, 'EMILIO MORALES', 'TLAXCALA', 44334455, 6);